version: "3.1"
services:
  db:
    image: mysql
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - delve_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    restart: always

volumes:
  delve_data: