version: "3.1"

services:
  mysql-service:
    image: mysql
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: d@t03am16qld
      MYSQL_USER: filemanager
      MYSQL_PASSWORD: fiMang@d4Abs65
    restart: always
    networks:
      - no-internet

  file-manager-service:
    image: openjdk:11
    container_name: file-manager
    command: bash -c "cd /file-manager && ./mvnw spring-boot:run"
    depends_on:
     - mysql-service
    ports:
      - "81:81"
    volumes:
      - ./service:/file-manager
    networks:
      - web
      - no-internet
    environment:
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-service:3306/file_management?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=fiMang@d4Abs65
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect

volumes:
  database_data:

networks:
  web:
    driver: bridge
  no-internet:
    driver: bridge
    internal: true

