version: "3.1"
services:
  db:
    image: mysql
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - delve_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: fiMang@d4Abs65
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    restart: always

#  raccoon:
#    image: debian/spring:latest
#    container_name: raccoon_spring
#    ports:
#      - "81:81"

volumes:
  delve_data:

