server:
  error:
    include-stacktrace: on-param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_management?createDatabaseIfNotExist=true
    username: root
    password: fiMang@d4Abs65
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect

