server:
  error:
    include-stacktrace: on-param
  port: 81
spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/file_management?createDatabaseIfNotExist=true
    username: root
    password: fiMang@d4Abs65
  jpa:
    hibernate:
      ddl-auto: update

