server:
  error:
    include-stacktrace: on-param
  port: 81
spring:
  datasource:
    url: jdbc:${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
